version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: db
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: perineum/foodgram_backend
    build:
      context: ../backend/foodgram/
      dockerfile: Dockerfile
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - frontend
  frontend:
    image: perineum/foodgram_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - media:/var/html/media/
      - static:/var/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
