# Generated by Django 4.2.5 on 2023-12-27 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранный рецепт',
                'verbose_name_plural': 'Избранные рецепты',
                'default_related_name': 'favorite',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название ингридиента', max_length=150, verbose_name='Ингридиент')),
                ('measurement_unit', models.CharField(help_text='Укажите единицу измерения', max_length=150, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngredientsForRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Укажите количество ингридиента', validators=[django.core.validators.MinValueValidator(0, 'Минимальное количество ингридиента 1')], verbose_name='Количество ингридиента')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Опишите инструкцию по приготовлению', verbose_name='Описание рецепта')),
                ('name', models.CharField(db_index=True, help_text='Введите название рецета', max_length=150, verbose_name='Название рецепта')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Укажите время приготовления рецепта', validators=[django.core.validators.MinValueValidator(1, 'Минимальное время приготовления')], verbose_name='Время приготовления')),
                ('image', models.ImageField(help_text='Добавьте изображение рецепта', upload_to='media/', verbose_name='Изображение рецепта')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
            ],
            options={
                'default_related_name': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Список покупок',
                'default_related_name': 'shopping_cart',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тега', max_length=150, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(help_text='Выберите цвета', max_length=150, unique=True, verbose_name='HEX цвета')),
                ('slug', models.SlugField(db_index=False, help_text='Укажите слаг', max_length=150, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
