# Generated by Django 4.2.5 on 2023-12-27 23:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Выберите цвета', image_field=None, max_length=150, samples=None, unique=True, verbose_name='HEX цвета'),
        ),
    ]
